name: photo_ai
description: "Photo filter AI new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  uni_links: ^0.5.1
  collection: ^1.18.0
  jwt_decoder: ^2.0.1

  # Local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # route
  go_router: ^13.2.0
  # Flutter helper
  #  flutter_native_splash: ^2.3.11
  pin_code_fields: ^8.0.1

  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.4
  path: ^1.9.0
  http_parser: ^4.0.2

  google_fonts: ^6.1.0
  google_mlkit_face_detection: ^0.11.0
  bot_toast: ^4.1.3
  tuple: ^2.0.2

  # build
  json_annotation: ^4.8.1
  freezed: ^2.4.7
  freezed_annotation:
  json_serializable: ^6.7.1
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: any
  in_app_purchase_android: any

  # State management
  flutter_bloc: ^8.1.4

  # DI
  get_it: ^7.6.7

  # Network
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  flutter_cache_manager: ^3.3.2

  # Firebase
  firebase_core: ^2.25.4
  firebase_analytics: ^10.8.5
  firebase_crashlytics: ^3.4.14
  firebase_messaging: ^14.7.15
  firebase_in_app_messaging: ^0.7.4+13
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.15.4

  video_player: ^2.8.2
  intl: 0.19.0
  device_preview: ^1.1.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  permission_handler: ^11.3.0
  carousel_slider: ^4.2.1
  volume_controller: ^2.0.7
  flutter_image_compress: ^2.1.0
  device_info_plus: ^9.1.2
  timeago: ^3.6.1

  # UI widget
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  popover: ^0.3.0
  photo_manager: ^3.1.1
  after_layout: ^1.2.0
  cached_network_image: ^3.3.1
  intro_slider: ^4.2.1
  modal_bottom_sheet: ^3.0.0-pre
  tiengviet: ^1.0.0
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.4
  flutter_html: ^3.0.0-beta.1
  barcode: ^2.2.6
  share_plus: ^7.2.2
  html: ^0.15.4
  dotted_decoration: ^2.0.0
  dots_indicator: ^3.0.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  flutter_share_me: ^1.4.0
  image_gallery_saver: ^2.0.3
  image: ^4.1.7
  lottie: ^3.1.0
  country_ip: ^3.0.0
  painter: ^2.0.0
  flutter_colorpicker: ^1.1.0
  widgets_to_image: ^1.0.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/bold/
    - assets/icons/outline/
    - assets/icons/custom/
    - assets/img/
    - assets/img/background/
    - assets/img/color/
    - assets/img/icon/
    - assets/loading/
flutter_intl:
  enabled: true
  class_name: AppLocale
  main_locale: vi
  arb_dir: lib/generated/l10n
  output_dir: lib/generated

flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: generated
  # Optional. Sets whether automatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: true
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: assets
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: Assets
  # Optional. Sets the filename split pattern for filename split. Default: [-_]
  filename_split_pattern: "[-_]"