// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDhWEMbjOAOLfEaP5ebkjgkfOsYkZ_Jw',
    appId: '1:829565695912:web:915f110a21978ed6390f9d',
    messagingSenderId: '829565695912',
    projectId: 'face2-4aa82',
    authDomain: 'face2-4aa82.firebaseapp.com',
    storageBucket: 'face2-4aa82.appspot.com',
    measurementId: 'G-2J241WE0VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1nqkiexU59DiCccYscE3vADpCydj0LQ',
    appId: '1:829565695912:android:e267db6349c7dd7e390f9d',
    messagingSenderId: '829565695912',
    projectId: 'face2-4aa82',
    storageBucket: 'face2-4aa82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERgSWU6orzdaJ0Wi4owEvUNukurshCtY',
    appId: '1:829565695912:ios:101f181f4c6b8aec390f9d',
    messagingSenderId: '829565695912',
    projectId: 'face2-4aa82',
    storageBucket: 'face2-4aa82.appspot.com',
    iosBundleId: 'vn.com.photoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERgSWU6orzdaJ0Wi4owEvUNukurshCtY',
    appId: '1:829565695912:ios:f94a5209ad74c5ae390f9d',
    messagingSenderId: '829565695912',
    projectId: 'face2-4aa82',
    storageBucket: 'face2-4aa82.appspot.com',
    iosBundleId: 'vn.com.photoAi.RunnerTests',
  );
}
